name: Run API Test with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  postman-newman-api-tests:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Check if ReqRes site is accessible
        run: curl -I https://reqres.in

      - name: Create CTRF json report
        run: npm run run-ctrf-report

      - name: Publish CTRF API Tests Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./ctrf/ctrf-report.json"
          suite-folded-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

  playwright-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Publish CTRF UI Tests Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./ctrf/ctrf-report-playwright.json"
          suite-folded-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
